# Virtual Port Configuration for JK-PB Waveshare Bridge

# IP address of the Waveshare RS485-to-Ethernet adapter
IP=10.0.0.3

# TCP port of the Waveshare (usually 9999)
PORT=9999

# Virtual serial port name
VIRTUAL_PORT=/dev/ttyV0
